# Generated by Django 4.1.3 on 2022-11-08 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='people_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animal',
            name='tasks',
            field=models.ManyToManyField(to='animal.task', verbose_name='tasks'),
        ),
        migrations.AddField(
            model_name='animal',
            name='vaccines',
            field=models.ManyToManyField(to='animal.vaccine', verbose_name='vaccines'),
        ),
    ]
