# Generated by Django 4.1.3 on 2022-11-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_remove_animal_tasks_remove_animal_vaccines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
