# Generated by Django 4.1.3 on 2022-11-10 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0007_rename_end_date_shoppinglist_ref_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='end_date',
            new_name='ref_date',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='animals',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='start_date',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='animal_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='animal.animal'),
            preserve_default=False,
        ),
    ]
