# Generated by Django 4.1.3 on 2022-11-10 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0008_rename_end_date_tasklist_ref_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='animal_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='animal.animal'),
        ),
    ]
