# Generated by Django 4.1.3 on 2022-11-08 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={},
        ),
        migrations.AlterModelManagers(
            name='people',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='people',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='people',
            name='email',
        ),
        migrations.RemoveField(
            model_name='people',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='people',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='people',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='people',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='people',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='people',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='people',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='people',
            name='password',
        ),
        migrations.RemoveField(
            model_name='people',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='people',
            name='username',
        ),
        migrations.AddField(
            model_name='people',
            name='cpf',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='people_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.people'),
        ),
        migrations.AlterField(
            model_name='myplan',
            name='people_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.people'),
        ),
    ]
