# Generated by Django 4.1.3 on 2022-11-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_people_options_alter_people_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='steet',
            new_name='street',
        ),
    ]
