# Generated by Django 4.1.3 on 2022-11-09 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_rename_steet_address_street'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='distrinct',
            new_name='district',
        ),
    ]
